export const DARKENED_LAYOUT_ON     = 'DARKENED_ON';
export const DARKENED_LAYOUT_OFF    = 'DARKENED_OFF';
export const DARKENED_LAYOUT_TOGGLE = 'DARKENED_TOGGLE';

export const DARKENED_ACTIONS = { DARKENED_LAYOUT_ON, DARKENED_LAYOUT_OFF, DARKENED_LAYOUT_TOGGLE};
