export const POPUP_CREATE_NOTE_TOGGLE = 'POPUP_CREATE_NOTE_TOGGLE';
export const POPUP_CREATE_NOTE_ON     = 'POPUP_CREATE_NOTE_ON';
export const POPUP_CREATE_NOTE_OFF    = 'POPUP_CREATE_NOTE_OFF';

export const POPUPS_ACTIONS = { POPUP_CREATE_NOTE_TOGGLE, POPUP_CREATE_NOTE_ON, POPUP_CREATE_NOTE_OFF };
